// svelte-app/src/components/UpdateBook.svelte
<script>
    export let id;
    export let bookData;
    export let onUpdateSuccess;
    export let onCancel;
    export let imageUrl; // Adicione a propriedade imageUrl

  
    let title = "";
    let author = "";
    let year = "";
    let publisher = "";
    let imageFile = null;
    let titleInput;
    let authorInput;
    let yearInput;
    let publisherInput;
  
    $: {
      if (bookData) {
        title = bookData.title;
        author = bookData.author;
        year = bookData.year;
        publisher = bookData.publisher;
      }
    }
  
    const updateBook = async () => {
      const formData = new FormData();
      formData.append("title", title);
      formData.append("author", author);
      formData.append("year", year);
      formData.append("publisher", publisher);
      if (imageFile) {
        formData.append("image", imageFile);
      }
  
      try {
        const response = await fetch(`http://localhost:3001/books/${id}`, {
          method: "PUT",
          body: formData,
        });
  
        if (response.ok) {
          onUpdateSuccess(); // Chame a função de sucesso passada como prop
        } else {
          console.error("Falha ao atualizar o livro:", response.statusText);
        }
      } catch (error) {
        console.error("Erro ao atualizar o livro:", error);
      }
    };
  
    function handleTitleInput(event) {
      title = event.target.value;
    }
  
    function handleAuthorInput(event) {
      author = event.target.value;
    }
  
    function handleYearInput(event) {
      year = event.target.value;
    }
  
    function handlePublisherInput(event) {
      publisher = event.target.value;
    }
  
    function handleFileInputChange(event) {
      const file = event.target.files[0];
      imageFile = file;
    }
  
    function cancelUpdate() {
      onCancel();
    }
  </script>
  
  <div class="register-container">
    <h2 class="register-title">Editar livro</h2>
    <img
      class="register-image"
      id="register-image-p"
      src={imageUrl}
      alt="Imagem atual"
    />
    <input
      class="register-input"
      type="file"
      accept="image/*"
      on:change={handleFileInputChange}
    />
    <input
      class="register-input"
      type="text"
      placeholder="Título"
      bind:this={titleInput}
      on:input={handleTitleInput}
      value={title}
    />
    <input
      class="register-input"
      type="text"
      placeholder="Autor(a)"
      bind:this={authorInput}
      on:input={handleAuthorInput}
      value={author}
    />
    <input
      class="register-input"
      type="text"
      placeholder="Ano de lançamento"
      bind:this={yearInput}
      on:input={handleYearInput}
      value={year}
    />
    <input
      class="register-input"
      type="text"
      placeholder="Editora"
      bind:this={publisherInput}
      on:input={handlePublisherInput}
      value={publisher}
    />
    <button class="register-button" on:click={() => updateBook(id)}>Salvar</button
    >
    <button class="register-button" type="button" on:click={cancelUpdate}
      >Cancelar</button
    >
  </div>

// solid-app/src/components/UpdateBook.jsx
import { createSignal } from 'solid-js';

const BASE_URL = 'http://localhost:3001'; // URL base da sua API

async function updateBook(updatedBook) {
  try {
      const formData = new FormData();
      formData.append('title', updatedBook.title);
      formData.append('author', updatedBook.author);
      formData.append('year', updatedBook.year);
      formData.append('publisher', updatedBook.publisher);

      // Adicione a imagem ao FormData apenas se uma nova imagem foi selecionada
      if (updatedBook.image instanceof File) {
          formData.append('image', updatedBook.image);
      }

      const response = await fetch(`${BASE_URL}/books/${updatedBook.id}`, {
          method: 'PUT',
          body: formData,
      });
      
      if (!response.ok) {
          throw new Error(`Erro ao atualizar livro: ${response.status} - ${response.statusText}`);
      }
      return true;
  } catch (error) {
      console.error('Erro ao atualizar livro:', error);
      return false;
  }
}

export function UpdateBook({ book, onUpdate, onCancel }) {
    const [updatedBook, setUpdatedBook] = createSignal(book);

    const handleSubmit = async (event) => {
        event.preventDefault();
        // Atualize o objeto updatedBook para incluir o ID do livro
        const updatedBookWithId = { ...updatedBook(), id: book._id };
        await updateBook(updatedBookWithId);
        onUpdate(updatedBookWithId); // Atualiza localmente o livro com os novos dados
    };
    

    const handleInputChange = (event) => {
        const { name, value } = event.target;
        setUpdatedBook((prevBook) => ({ ...prevBook, [name]: value }));
    };

    const handleImageChange = (event) => {
        // Define a nova imagem selecionada no estado, apenas se for uma instância de File
        const newImage = event.target.files[0];
        if (newImage instanceof File) {
            setUpdatedBook((prevBook) => ({ ...prevBook, image: newImage }));
        }
    };

    return (
        <div className='register-container'>
            <h2 className='register-title'>Editar livro</h2>
            <form onSubmit={handleSubmit}>
                {book.image && (
                    <img
                        id='register-image-p'
                        className='register-image'
                        src={`${BASE_URL}/uploads/${book.image}`}
                        alt="Book"
                    />
                )}
                <input className='register-input' type="file" accept="image/*" onChange={handleImageChange} />
                <input className='register-input' type="text" placeholder='Título' name="title" value={updatedBook().title} onInput={handleInputChange} />
                <input className='register-input' type="text" placeholder='Autor(a)' name="author" value={updatedBook().author} onInput={handleInputChange} />
                <input className='register-input' type="text" placeholder='Ano de lançamento' name="year" value={updatedBook().year} onInput={handleInputChange} />
                <input className='register-input' type="text" placeholder='Editora' name="publisher" value={updatedBook().publisher} onInput={handleInputChange} />
                <button className='register-button' type="submit">Salvar</button>
                <button className='register-button' type="button" onClick={onCancel}>Cancelar</button>
            </form>
        </div>
    );
}
